name: Inform
main: com.kingsandglory.Inform
version: 0.0
commands:
    wut:
        description: Wut
        usage: /wut
        #permission: Inform.recieve
        #permission-message: Inform.recieve