name: Inform
main: com.kingsandglory.Inform
version: 1.1
commands:
    wut:
        description: Wut, a throwaway easter egg command. §cYAY§c
        usage: /wut
        #permission: Inform.recieve
        #permission-message: Inform.recieve